name: Generate contribution snake

on:
  schedule:
    - cron: "17 8 * * *"
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - ".github/workflows/snake.yml"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: kjmagill
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh contribution snake"
